### ISSUE TITLE
Nextjs example ConnectError: Failed to parse URL (digest: undefined)

### ISSUE THREAD

**Issue by jvmiert** [bufbuild/connect-es-integration#609]
If I add the following code to the [index page](https://github.com/bufbuild/connect-es-integration/blob/main/nextjs/pages/index.tsx) in the Nextjs example:
```javascript
  const [sentHello, setSentHello] = useState<boolean>(false);
  if (!sentHello) {
    send("hello");
    setSentHello(true);
  }
```

I get the following error:
```
- error unhandledRejection: Error [ConnectError]: [unknown] Failed to parse URL from /api/buf.connect.demo.eliza.v1.ElizaService/Introduce
    at Function.from (file:///C:/Users/x/Desktop/connect-es-integration/nextjs/node_modules/@bufbuild/connect/dist/esm/connect-error.js:70:20)
    at abort (file:///C:/Users/x/Desktop/connect-es-integration/nextjs/node_modules/@bufbuild/connect/dist/esm/protocol/run-call.js:86:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.stream (file:///C:/Users/x/Desktop/connect-es-integration/nextjs/node_modules/@bufbuild/connect-web/dist/esm/connect-transport.js:129:20) {
  digest: undefined
```

I get a similiar error on the actual project that I'm working on. It seems it might be related to the edge runtime of Nextjs:
```
- error unhandledRejection: Error [TypeError]: Cannot read properties of undefined (reading 'flags')
    at setRemoved (C:\Users\x\node_modules\next\dist\compiled\@edge-runtime\primitives\events.js:488:3)
    at removeListenerAt (C:\Users\x\node_modules\next\dist\compiled\@edge-runtime\primitives\events.js:554:3)
    at EventTarget.dispatchEvent (C:\Users\x\node_modules\next\dist\compiled\@edge-runtime\primitives\events.js:627:33)
    at abortSignalAbort (C:\Users\x\node_modules\next\dist\compiled\@edge-runtime\primitives\abort-controller.js:63:10)
    at AbortController.abort (C:\Users\x\node_modules\next\dist\compiled\@edge-runtime\primitives\abort-controller.js:74:5)
    at abort (file:///C:/Users/x/node_modules/@bufbuild/connect/dist/esm/protocol/run-call.js:87:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.unary (file:///C:/Users/x/node_modules/@bufbuild/connect-web/dist/esm/connect-transport.js:45:20)
    at async Object.getProduct (file:///C:/Users/x/node_modules/@bufbuild/connect/dist/esm/promise-client.js:66:26) {
  digest: undefined
```
Does this mean I cannot use Connect on the server side? Or is this an issue with either Connect or Nextjs?

EDIT: I think these are 2 separate issues that I'm seeing. In the actual project I'm not using `@bufbuild/connect-next` but I'm using `@bufbuild/connect` and `@bufbuild/connect-web`. When I downgrade these to 0.8.6 the error goes away. I will try to reproduce it in a simpler version.

**Comment by smaye81** [comment]
Your first issue (using `sentHello`) is failing because Next.js performs static-site generation by default ([docs](https://nextjs.org/docs/pages/building-your-application/rendering/static-site-generation)) and by adding that data fetch where you have it (on load), it is causing that code to run on the dev server in Node. The way this code typically runs (via the `onClick` event) is on the client-side.

You have a few options depending on what you're trying to accomplish:

* If you truly want to use server-side data fetching, then you'll have to do the following:
   1. Put the call in `getServerSideProps` or `getStaticProps` so that bit of code is run in Node and is allowed to use modules that can only run in the Node.js environment.
   2. Change the `baseUrl` in your transport to be `http://0.0.0.0:3000/api`. Using just `/api` won't work as the URL when running on the server.

* If you want to run this on load, but want the data to be fetched client-side, use a React `useEffect`, which tells Next.js to use client-side fetching ([docs](https://nextjs.org/docs/pages/building-your-application/data-fetching/client-side)):

```typescript
useEffect(() => {
   if (!sentHello) {
      send("hello");
      setSentHello(c => !c);
   }
}, []);
```

All that being said, this is admittedly not easy to figure out. I will talk to the team to see how we can make this process easier / more clear.

As for your second issue `(reading 'flags')`, I'm not entirely sure without knowing more of your environment. We don't offer support for the Edge runtime yet, so that's a fair guess.

Let me know if this helps.

**Comment by jvmiert** [comment]
Thank you for the extensive reply @smaye81! Apologies for the red herring code snippet that I shared initially. It was a failed attempt at a simplied repro for the "flags" issue I was seeing in my code base. I think the examples are great and don't need further clarification!

Here's a more accurate repro of the issue: https://github.com/jvmiert/connect-es-issue/blob/main/pages/index.tsx#L12

This works fine with `@bufbuild/connect` and `@bufbuild/connect-web` 0.8.6 but breaks with 0.9.0 with the flags error.

**Comment by jvmiert** [comment]
I can confirm that installing the latest Nextjs canary fixes the issue in both node 16 and node 18 for me. Thanks again for taking the time to investigate.

Just wanted to share that I've really enjoyed the developer experience so far using both the Buf CLI and the Connect protocol. Keep up the great work!

**Comment by smaye81** [comment]
That's great @jvmiert. Glad it worked for you. Thanks for the kind words. Going to close this issue, but if something else turns up, feel free to open a new one.
